apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: paulsony/kubedemo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
