apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: webapp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8501
  selector:
    app: webapp
  sessionAffinity: None
